
import { GiaiDoan } from './types';
import { STAGE_1_EGG, STAGE_2_CRACKED, STAGE_3_BABY, STAGE_4_TEEN, STAGE_5_ADULT, GHOST, POOP } from './gameData/pet';
import { PHOENIX_EGG_FRAMES, PHOENIX_CRACKED_FRAMES, PHOENIX_BABY_FRAMES, PHOENIX_TEEN_FRAMES, PHOENIX_ADULT_FRAMES } from './gameData/phoenix';
import { DRAGON_EGG_FRAMES, DRAGON_CRACKED_FRAMES, DRAGON_BABY_FRAMES, DRAGON_TEEN_FRAMES, DRAGON_ADULT_FRAMES } from './gameData/dragon';
import { FOREST_EGG_FRAMES, FOREST_CRACKED_FRAMES, FOREST_BABY_FRAMES, FOREST_TEEN_FRAMES, FOREST_ADULT_FRAMES } from './gameData/treant';
import { THUNDER_EGG_FRAMES, THUNDER_CRACKED_FRAMES, THUNDER_BABY_FRAMES, THUNDER_TEEN_FRAMES, THUNDER_ADULT_FRAMES } from './gameData/thunder';
import { SHADOW_EGG, SHADOW_CRACKED, SHADOW_BABY, SHADOW_TEEN, SHADOW_ADULT } from './gameData/shadow';

// Re-export everything for compatibility
export * from './gameData/config';
export * from './gameData/sky';
export * from './gameData/plants';
export * from './gameData/pet';

// Mapping frames for Chicken (Already arrays of frames)
const CHICKEN_FRAMES = {
  [GiaiDoan.TRUNG]: { IDLE: STAGE_1_EGG, HAPPY: STAGE_1_EGG },
  [GiaiDoan.NUT_VO]: { IDLE: STAGE_2_CRACKED, HAPPY: STAGE_2_CRACKED },
  [GiaiDoan.SO_SINH]: { IDLE: STAGE_3_BABY, HAPPY: STAGE_3_BABY },
  [GiaiDoan.THIEU_NIEN]: { IDLE: STAGE_4_TEEN, HAPPY: STAGE_4_TEEN },
  [GiaiDoan.TRUONG_THANH]: { IDLE: STAGE_5_ADULT, HAPPY: STAGE_5_ADULT },
  [GiaiDoan.HON_MA]: { IDLE: GHOST, HAPPY: GHOST },
  POOP: POOP
};

// Mapping frames for Phoenix (Now using full animation frames)
const PHOENIX_FRAMES = {
  [GiaiDoan.TRUNG]: { IDLE: PHOENIX_EGG_FRAMES, HAPPY: PHOENIX_EGG_FRAMES },
  [GiaiDoan.NUT_VO]: { IDLE: PHOENIX_CRACKED_FRAMES, HAPPY: PHOENIX_CRACKED_FRAMES },
  [GiaiDoan.SO_SINH]: { IDLE: PHOENIX_BABY_FRAMES, HAPPY: PHOENIX_BABY_FRAMES },
  [GiaiDoan.THIEU_NIEN]: { IDLE: PHOENIX_TEEN_FRAMES, HAPPY: PHOENIX_TEEN_FRAMES }, 
  [GiaiDoan.TRUONG_THANH]: { IDLE: PHOENIX_ADULT_FRAMES, HAPPY: PHOENIX_ADULT_FRAMES },
  [GiaiDoan.HON_MA]: { IDLE: GHOST, HAPPY: GHOST },
  POOP: POOP
};

// Mapping frames for Ice Dragon (Updated to use full animation frames)
const DRAGON_FRAMES = {
  [GiaiDoan.TRUNG]: { IDLE: DRAGON_EGG_FRAMES, HAPPY: DRAGON_EGG_FRAMES },
  [GiaiDoan.NUT_VO]: { IDLE: DRAGON_CRACKED_FRAMES, HAPPY: DRAGON_CRACKED_FRAMES },
  [GiaiDoan.SO_SINH]: { IDLE: DRAGON_BABY_FRAMES, HAPPY: DRAGON_BABY_FRAMES },
  [GiaiDoan.THIEU_NIEN]: { IDLE: DRAGON_TEEN_FRAMES, HAPPY: DRAGON_TEEN_FRAMES }, 
  [GiaiDoan.TRUONG_THANH]: { IDLE: DRAGON_ADULT_FRAMES, HAPPY: DRAGON_ADULT_FRAMES },
  [GiaiDoan.HON_MA]: { IDLE: GHOST, HAPPY: GHOST },
  POOP: POOP
};

// Mapping frames for Forest Guardian (Treant)
const TREANT_FRAMES = {
  [GiaiDoan.TRUNG]: { IDLE: FOREST_EGG_FRAMES, HAPPY: FOREST_EGG_FRAMES },
  [GiaiDoan.NUT_VO]: { IDLE: FOREST_CRACKED_FRAMES, HAPPY: FOREST_CRACKED_FRAMES },
  [GiaiDoan.SO_SINH]: { IDLE: FOREST_BABY_FRAMES, HAPPY: FOREST_BABY_FRAMES },
  [GiaiDoan.THIEU_NIEN]: { IDLE: FOREST_TEEN_FRAMES, HAPPY: FOREST_TEEN_FRAMES }, 
  [GiaiDoan.TRUONG_THANH]: { IDLE: FOREST_ADULT_FRAMES, HAPPY: FOREST_ADULT_FRAMES },
  [GiaiDoan.HON_MA]: { IDLE: GHOST, HAPPY: GHOST },
  POOP: POOP
};

// Mapping frames for Thunder God (Raiju)
const THUNDER_FRAMES = {
  [GiaiDoan.TRUNG]: { IDLE: THUNDER_EGG_FRAMES, HAPPY: THUNDER_EGG_FRAMES },
  [GiaiDoan.NUT_VO]: { IDLE: THUNDER_CRACKED_FRAMES, HAPPY: THUNDER_CRACKED_FRAMES },
  [GiaiDoan.SO_SINH]: { IDLE: THUNDER_BABY_FRAMES, HAPPY: THUNDER_BABY_FRAMES },
  [GiaiDoan.THIEU_NIEN]: { IDLE: THUNDER_TEEN_FRAMES, HAPPY: THUNDER_TEEN_FRAMES }, 
  [GiaiDoan.TRUONG_THANH]: { IDLE: THUNDER_ADULT_FRAMES, HAPPY: THUNDER_ADULT_FRAMES },
  [GiaiDoan.HON_MA]: { IDLE: GHOST, HAPPY: GHOST },
  POOP: POOP
};

// Mapping frames for Nightmare Horse (Hac Ma)
const SHADOW_FRAMES = {
  [GiaiDoan.TRUNG]: { IDLE: [SHADOW_EGG], HAPPY: [SHADOW_EGG] },
  [GiaiDoan.NUT_VO]: { IDLE: [SHADOW_CRACKED], HAPPY: [SHADOW_CRACKED] },
  [GiaiDoan.SO_SINH]: { IDLE: [SHADOW_BABY], HAPPY: [SHADOW_BABY] },
  [GiaiDoan.THIEU_NIEN]: { IDLE: [SHADOW_TEEN], HAPPY: [SHADOW_TEEN] }, 
  [GiaiDoan.TRUONG_THANH]: { IDLE: [SHADOW_ADULT], HAPPY: [SHADOW_ADULT] },
  [GiaiDoan.HON_MA]: { IDLE: GHOST, HAPPY: GHOST },
  POOP: POOP
};

// Master Frame Object
export const PET_FRAMES = {
  'GA': CHICKEN_FRAMES,
  'PHUONG_HOANG': PHOENIX_FRAMES,
  'RONG_BANG': DRAGON_FRAMES,
  'THAN_RUNG': TREANT_FRAMES,
  'LOI_THAN': THUNDER_FRAMES,
  'HAC_MA': SHADOW_FRAMES
};

// Keep the old FRAMES export for backward compatibility if needed, aliasing to Chicken
export const FRAMES = CHICKEN_FRAMES;
